# Generated by Django 3.2.2 on 2021-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='phone_or_email')),
                ('code', models.PositiveIntegerField(verbose_name='verification code')),
                ('verified', models.BooleanField(default=False, verbose_name='verification account')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date and time created')),
            ],
        ),
    ]
