# Generated by Django 3.2 on 2021-04-26 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date and time created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='identifier',
            field=models.CharField(max_length=255, unique=True, verbose_name='phone_or_email'),
        ),
    ]
