# Generated by Django 3.2.2 on 2021-12-20 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Describe shop')),
                ('wait_cash_days_average', models.IntegerField(default=90)),
                ('wait_cash_days_maximum', models.IntegerField(default=180)),
                ('url', models.URLField(null=True, verbose_name='Link company')),
                ('sale', models.FloatField()),
                ('sale_to', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='shops/', verbose_name='Avatar company')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_set', to='shop.groupshop')),
            ],
        ),
    ]
