# Generated by Django 3.2 on 2021-04-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='Название')),
                ('description', models.CharField(max_length=160, null=True, verbose_name='Описание')),
                ('players', models.PositiveSmallIntegerField(default=3, verbose_name='Кол-во участников')),
                ('winners', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во победилей')),
                ('energy', models.PositiveSmallIntegerField(default=1, verbose_name='Затрата энергии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активность игры')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='lot/')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lot.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Youtube', max_length=32)),
                ('link', models.URLField()),
                ('icon', models.CharField(default='cloud', max_length=32)),
                ('color', models.CharField(default='#ffffff', max_length=16)),
                ('subscribe', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('repost', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_set', to='lot.lot')),
            ],
        ),
    ]
