# Generated by Django 3.2.2 on 2021-08-29 16:33

from django.db import migrations
import my_user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', my_user.manager.UserManager()),
            ],
        ),
    ]
