# Generated by Django 3.2 on 2021-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='email or phone'),
            preserve_default=False,
        ),
    ]
